repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      additional_dependencies: ["click==8.0.4"]

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.2
    hooks:
    - id: isort
      args: ["--profile", "black"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    - id: mypy
      name: mypy-fv3core
      args: [
          --config-file, setup.cfg,
        ]
      files: fv3core
      exclude: |
        (?x)^(
        fv3core/pace/fv3core/stencils/fv_subgridz.py |
        fv3core/tests/conftest.py
        )$
    - id: mypy
      name: mypy-util
      args: [
          --config-file, setup.cfg
        ]
      files: ^util
    - id: mypy
      name: mypy-stencils
      args: [
          --config-file, setup.cfg
        ]
      files: stencils
      exclude: |
        (?x)^(
        stencils/pace/stencils/testing/grid.py |
        )$
    - id: mypy
      name: mypy-driver
      args: [
          --config-file, setup.cfg
        ]
      files: driver
      exclude: |
        (?x)^(
        tests/main/driver/__init__.py |
        )$
    - id: mypy
      name: mypy-physics
      args: [
          --config-file, setup.cfg
        ]
      files: physics
    - id: mypy
      name: mypy-dsl
      args: [
          --config-file, setup.cfg
        ]
      files: dsl
      exclude: |
        (?x)^(
        dsl/pace/dsl/gt4py_utils.py |
        )$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      name: flake8
      language_version: python3
      args: [--config, setup.cfg]
      exclude: |
        (?x)^(
        .*/__init__.py |
        )$
    - id: flake8
      name: flake8 __init__.py files
      files: "__init__.py"
      # ignore unused import error in __init__.py files
      args: ["--ignore=F401,E203", --config, setup.cfg]
